services:
  - type: web
    name: nasa-space-app-api
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.16
      - key: FLASK_ENV
        value: production
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_USE_PEP517
        value: "0"
